spring.application.name=ticketing

spring.r2dbc.url=r2dbc:postgresql://${RDS_HOST}:${RDS_PORT:5432}/${RDS_DB}
spring.r2dbc.username=${RDS_USER}
spring.r2dbc.password=${RDS_PASSWORD}
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=${R2DBC_POOL_MAX:30}
spring.r2dbc.pool.max-idle-time=10m

spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.transport.protocol=smtp
spring.mail.default.encoding=UTF-8

spring.jwt.secret=${JWT_SECRET}
spring.expiration-ms=604800000
spring.queue-ttl=2h
spring.access-ttl=10m

logging.level.org.example.ticketing=INFO
logging.level.org.springframework.mail=WARN

toss.secret.key=${TOSS_SECRET_KEY}
toss.client.key=${TOSS_CLIENT_KEY}
toss.payments.api-url=https://api.tosspayments.com/v1/payments

reservation.hold-ttl=3m
